package com.designtravel.seeder;

import com.designtravel.model.Destination;
import com.designtravel.model.NearbyPlace;
import com.designtravel.model.Place;
import com.designtravel.repository.DestinationRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.CommandLineRunner;
import org.springframework.data.mongodb.core.geo.GeoJsonPoint;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public class DataSeeder implements CommandLineRunner {

    private static final Logger log = LoggerFactory.getLogger(DataSeeder.class);

    private final DestinationRepository destinationRepository;

    public DataSeeder(DestinationRepository destinationRepository) {
        this.destinationRepository = destinationRepository;
    }

    @Override
    public void run(String... args) {
        try {
            if (destinationRepository.count() == 0) {
                log.info("No destinations found in MongoDB. Seeding curated editorial destinations...");
                seedDestinations();
                log.info("Successfully seeded 12 global destinations into MongoDB.");
            } else {
                log.info("Destinations collection already populated with {} records.", destinationRepository.count());
            }
        } catch (Exception ex) {
            log.warn("MongoDB seeding was bypassed or connection was deferred: {}. App will serve fallbacks if needed.", ex.getMessage());
        }
    }

    private void seedDestinations() {
        List<Destination> destinations = List.of(
            // 1. Kyoto, Japan
            Destination.builder()
                .name("Kyoto")
                .country("Japan")
                .continent("Asia")
                .tagline("The timeless cultural sanctuary of ancient Japan")
                .description("Kyoto is the historic heartbeat of Japan, home to over a thousand classical Buddhist temples, serene Zen rock gardens, centuries-old wooden teahouses, and the mystical bamboo groves of Arashiyama.")
                .location(new GeoJsonPoint(135.7681, 35.0116))
                .latitude(35.0116)
                .longitude(135.7681)
                .coverImageUrl("https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1600&q=85")
                .heroVideoUrl("https://assets.mixkit.co/videos/preview/mixkit-japan-traditional-temple-garden-42617-large.mp4")
                .bestSeason("March - May & October - November")
                .currency("JPY (¥)")
                .language("Japanese")
                .avgDailyBudgetUSD(140)
                .rating(4.9)
                .reviewCount(3420)
                .tags(List.of("Culture", "Temples", "Gastronomy", "Heritage", "Zen"))
                .places(List.of(
                    Place.builder()
                        .id("kyo-1")
                        .name("Fushimi Inari-taisha")
                        .category("Sacred Shrine")
                        .description("Winding paths beneath thousands of vivid vermilion torii gates stretching along the slopes of sacred Mount Inari.")
                        .imageUrl("https://images.unsplash.com/photo-1478436127897-769e00d2c715?auto=format&fit=crop&w=800&q=80")
                        .entryFee("Free")
                        .openingHours("Open 24 Hours")
                        .rating(4.9)
                        .latitude(34.9671)
                        .longitude(135.7727)
                        .bestTimeToVisit("Sunrise (06:00 - 07:30 AM)")
                        .build(),
                    Place.builder()
                        .id("kyo-2")
                        .name("Arashiyama Bamboo Grove")
                        .category("Natural Wonder")
                        .description("Towering emerald stalks of bamboo that rustle softly in the wind, creating an otherworldly sensory sanctuary.")
                        .imageUrl("https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=800&q=80")
                        .entryFee("Free")
                        .openingHours("Open 24 Hours")
                        .rating(4.8)
                        .latitude(35.0166)
                        .longitude(135.6713)
                        .bestTimeToVisit("Early morning before 08:00 AM")
                        .build(),
                    Place.builder()
                        .id("kyo-3")
                        .name("Kinkaku-ji (The Golden Pavilion)")
                        .category("Architectural Masterpiece")
                        .description("A breathtaking Zen Buddhist temple whose top two floors are completely covered in pure gold leaf, reflecting over Mirror Lake.")
                        .imageUrl("https://images.unsplash.com/photo-1545569341-9eb8b30979d9?auto=format&fit=crop&w=800&q=80")
                        .entryFee("¥500 (~$3.50)")
                        .openingHours("09:00 AM - 05:00 PM")
                        .rating(4.8)
                        .latitude(35.0394)
                        .longitude(135.7292)
                        .bestTimeToVisit("Late afternoon golden hour")
                        .build()
                ))
                .build(),

            // 2. Paris, France
            Destination.builder()
                .name("Paris")
                .country("France")
                .continent("Europe")
                .tagline("The global capital of art, haute cuisine, and timeless romance")
                .description("Washed in honey-colored limestone and bisected by the Seine, Paris captivates with grand neoclassical boulevards, world-class museums, intimate pavement bistros, and iconic architectural silhouettes.")
                .location(new GeoJsonPoint(2.3522, 48.8566))
                .latitude(48.8566)
                .longitude(2.3522)
                .coverImageUrl("https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1600&q=85")
                .heroVideoUrl("https://assets.mixkit.co/videos/preview/mixkit-aerial-view-of-the-eiffel-tower-in-paris-42999-large.mp4")
                .bestSeason("April - June & September - November")
                .currency("EUR (€)")
                .language("French")
                .avgDailyBudgetUSD(190)
                .rating(4.8)
                .reviewCount(5890)
                .tags(List.of("Art", "Gastronomy", "Romance", "Architecture", "Luxury"))
                .places(List.of(
                    Place.builder()
                        .id("par-1")
                        .name("Musée du Louvre & Tuileries")
                        .category("World Museum")
                        .description("The world's foremost art museum, housing the Mona Lisa and Winged Victory inside a palace of French royalty.")
                        .imageUrl("https://images.unsplash.com/photo-1499856871958-5b9627545d1a?auto=format&fit=crop&w=800&q=80")
                        .entryFee("€22 (~$24)")
                        .openingHours("09:00 AM - 06:00 PM (Closed Tue)")
                        .rating(4.9)
                        .latitude(48.8606)
                        .longitude(2.3376)
                        .bestTimeToVisit("Wednesday or Friday evening")
                        .build(),
                    Place.builder()
                        .id("par-2")
                        .name("Eiffel Tower & Champ de Mars")
                        .category("Iconic Monument")
                        .description("Gustave Eiffel's wrought-iron lattice tower illuminating the Parisian sky with sparkles every hour on the hour.")
                        .imageUrl("https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?auto=format&fit=crop&w=800&q=80")
                        .entryFee("€18 - €29")
                        .openingHours("09:30 AM - 11:45 PM")
                        .rating(4.7)
                        .latitude(48.8584)
                        .longitude(2.2945)
                        .bestTimeToVisit("Sunset into twilight sparkle")
                        .build(),
                    Place.builder()
                        .id("par-3")
                        .name("Montmartre & Sacré-Cœur")
                        .category("Bohemian Quarter")
                        .description("Cobbled streets where Monet and Picasso painted, crowned by the radiant white dome overlooking Paris.")
                        .imageUrl("https://images.unsplash.com/photo-1520939817895-060bdef4ad1b?auto=format&fit=crop&w=800&q=80")
                        .entryFee("Free")
                        .openingHours("06:30 AM - 10:30 PM")
                        .rating(4.8)
                        .latitude(48.8867)
                        .longitude(2.3431)
                        .bestTimeToVisit("Early morning for tranquil streets")
                        .build()
                ))
                .build(),

            // 3. Banff & Lake Louise, Canada
            Destination.builder()
                .name("Banff")
                .country("Canada")
                .continent("Americas")
                .tagline("Untamed alpine splendor in the heart of the Canadian Rockies")
                .description("Banff National Park is a realm of turquoise glacial lakes, jagged snow-capped limestone peaks, roaming wildlife, and world-class alpine wilderness adventures.")
                .location(new GeoJsonPoint(-115.5708, 51.1784))
                .latitude(51.1784)
                .longitude(-115.5708)
                .coverImageUrl("https://images.unsplash.com/photo-1503614472-8c93d56e92ce?auto=format&fit=crop&w=1600&q=85")
                .heroVideoUrl("https://assets.mixkit.co/videos/preview/mixkit-lake-surrounded-by-mountains-under-a-blue-sky-42981-large.mp4")
                .bestSeason("June - September (Hiking) & Dec - March (Skiing)")
                .currency("CAD ($)")
                .language("English")
                .avgDailyBudgetUSD(170)
                .rating(4.9)
                .reviewCount(2180)
                .tags(List.of("Nature", "Mountains", "Adventure", "Lakes", "Wildlife"))
                .places(List.of(
                    Place.builder()
                        .id("bnf-1")
                        .name("Moraine Lake & Valley of the Ten Peaks")
                        .category("Glacial Wonder")
                        .description("Vivid azure waters fed by glaciers, cradled in a dramatic ring of ten monumental Canadian peaks.")
                        .imageUrl("https://images.unsplash.com/photo-1517411032315-54ef2cb783bb?auto=format&fit=crop&w=800&q=80")
                        .entryFee("National Park Pass ($10.50 CAD)")
                        .openingHours("Shuttle access: 06:30 AM - 07:00 PM")
                        .rating(5.0)
                        .latitude(51.3217)
                        .longitude(-116.1860)
                        .bestTimeToVisit("Sunrise from the Rockpile")
                        .build(),
                    Place.builder()
                        .id("bnf-2")
                        .name("Lake Louise & Fairmont Chateau")
                        .category("Alpine Lake")
                        .description("World-renowned turquoise lake with striking views of Victoria Glacier, offering canoe rentals and tea house trails.")
                        .imageUrl("https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80")
                        .entryFee("Park Pass Required")
                        .openingHours("Open 24 Hours")
                        .rating(4.9)
                        .latitude(51.4254)
                        .longitude(-116.1773)
                        .bestTimeToVisit("Morning hike to Agnes Lake Tea House")
                        .build()
                ))
                .build(),

            // 4. Rome, Italy
            Destination.builder()
                .name("Rome")
                .country("Italy")
                .continent("Europe")
                .tagline("The eternal city of emperors, baroque piazzas, and culinary joy")
                .description("Rome is a living, breathing museum where three millennia of human history intertwine with vibrant street life, artisan espresso bars, and candlelit trattorias serving carbonara and cacio e pepe.")
                .location(new GeoJsonPoint(12.4964, 41.9028))
                .latitude(41.9028)
                .longitude(12.4964)
                .coverImageUrl("https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=1600&q=85")
                .heroVideoUrl("https://assets.mixkit.co/videos/preview/mixkit-colosseum-in-rome-sunset-42998-large.mp4")
                .bestSeason("April - May & September - October")
                .currency("EUR (€)")
                .language("Italian")
                .avgDailyBudgetUSD(160)
                .rating(4.8)
                .reviewCount(4780)
                .tags(List.of("History", "Architecture", "Gastronomy", "Heritage", "Romance"))
                .places(List.of(
                    Place.builder()
                        .id("rom-1")
                        .name("The Colosseum & Roman Forum")
                        .category("Ancient Wonder")
                        .description("The monumental amphitheater of gladiatorial contests standing at the epicenter of the Roman Empire.")
                        .imageUrl("https://images.unsplash.com/photo-1515542622106-78bda8ba0e5b?auto=format&fit=crop&w=800&q=80")
                        .entryFee("€18 (~$20)")
                        .openingHours("09:00 AM - 07:00 PM")
                        .rating(4.9)
                        .latitude(41.8902)
                        .longitude(12.4922)
                        .bestTimeToVisit("Early morning opening ticket")
                        .build(),
                    Place.builder()
                        .id("rom-2")
                        .name("Pantheon & Piazza della Rotonda")
                        .category("Architectural Marvel")
                        .description("Nearly 2,000-year-old temple featuring the world's largest unreinforced concrete dome and glowing oculus.")
                        .imageUrl("https://images.unsplash.com/photo-1531572753322-ad063cecc140?auto=format&fit=crop&w=800&q=80")
                        .entryFee("€5 (~$5.50)")
                        .openingHours("09:00 AM - 07:00 PM")
                        .rating(4.8)
                        .latitude(41.8986)
                        .longitude(12.4769)
                        .bestTimeToVisit("Midday when sunlight beams through the oculus")
                        .build()
                ))
                .build(),

            // 5. Bali, Indonesia
            Destination.builder()
                .name("Bali")
                .country("Indonesia")
                .continent("Asia")
                .tagline("Island of the Gods, emerald rice terraces, and coastal bliss")
                .description("An intoxicating sanctuary of sacred water temples, artistic village craft guilds, dramatic clifftop surf breaks, and restorative wellness retreats.")
                .location(new GeoJsonPoint(115.1889, -8.4095))
                .latitude(-8.4095)
                .longitude(115.1889)
                .coverImageUrl("https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1600&q=85")
                .heroVideoUrl("https://assets.mixkit.co/videos/preview/mixkit-aerial-view-of-a-resort-with-palm-trees-in-bali-43020-large.mp4")
                .bestSeason("April - October (Dry season)")
                .currency("IDR (Rp)")
                .language("Indonesian / Balinese")
                .avgDailyBudgetUSD(85)
                .rating(4.8)
                .reviewCount(3940)
                .tags(List.of("Beaches", "Wellness", "Nature", "Culture", "Tropical"))
                .places(List.of(
                    Place.builder()
                        .id("bal-1")
                        .name("Tegalalang Rice Terraces")
                        .category("Cultural Landscape")
                        .description("Stepped emerald green paddy fields sculpted across the valley with centuries-old subak irrigation.")
                        .imageUrl("https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?auto=format&fit=crop&w=800&q=80")
                        .entryFee("IDR 25,000 (~$1.70)")
                        .openingHours("08:00 AM - 06:00 PM")
                        .rating(4.7)
                        .latitude(-8.4312)
                        .longitude(115.2792)
                        .bestTimeToVisit("07:00 AM for misty morning lighting")
                        .build(),
                    Place.builder()
                        .id("bal-2")
                        .name("Uluwatu Clifftop Temple")
                        .category("Sacred Sea Temple")
                        .description("Perched atop a 70-meter limestone cliff towering over crashing Indian Ocean swells, hosting nightly Kecak fire dances.")
                        .imageUrl("https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&w=800&q=80")
                        .entryFee("IDR 50,000 (~$3.50)")
                        .openingHours("07:00 AM - 07:00 PM")
                        .rating(4.8)
                        .latitude(-8.8291)
                        .longitude(115.0849)
                        .bestTimeToVisit("05:30 PM for sunset & dance")
                        .build()
                ))
                .build(),

            // 6. Cape Town, South Africa
            Destination.builder()
                .name("Cape Town")
                .country("South Africa")
                .continent("Africa")
                .tagline("Where dramatic ocean horizons meet majestic table mountains")
                .description("A breathtaking coastal enclave nestled between the iconic flat-topped Table Mountain, dramatic Atlantic swells, award-winning winelands, and colonies of African penguins.")
                .location(new GeoJsonPoint(18.4241, -33.9249))
                .latitude(-33.9249)
                .longitude(18.4241)
                .coverImageUrl("https://images.unsplash.com/photo-1580618672591-eb180b1a973f?auto=format&fit=crop&w=1600&q=85")
                .heroVideoUrl("https://assets.mixkit.co/videos/preview/mixkit-aerial-view-of-cape-town-coastline-42990-large.mp4")
                .bestSeason("November - March (Summer)")
                .currency("ZAR (R)")
                .language("English / Afrikaans")
                .avgDailyBudgetUSD(110)
                .rating(4.9)
                .reviewCount(2610)
                .tags(List.of("Mountains", "Wine", "Coast", "Adventure", "Wildlife"))
                .places(List.of(
                    Place.builder()
                        .id("cpt-1")
                        .name("Table Mountain Aerial Cableway")
                        .category("Geological Wonder")
                        .description("Revolving cable car ascent to the flat summit overlooking the two oceans and city bowl.")
                        .imageUrl("https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80")
                        .entryFee("R390 (~$22)")
                        .openingHours("08:30 AM - 06:30 PM")
                        .rating(4.9)
                        .latitude(-33.9628)
                        .longitude(18.4098)
                        .bestTimeToVisit("Clear morning when no 'tablecloth' cloud is present")
                        .build()
                ))
                .build(),

            // 7. Reykjavik, Iceland
            Destination.builder()
                .name("Reykjavik")
                .country("Iceland")
                .continent("Europe")
                .tagline("The celestial realm of northern lights, geothermal springs, and waterfalls")
                .description("The gateway to an untamed volcanic frontier of black sand beaches, dancing aurora borealis, roaring glacial waterfalls, and natural thermal lagoons.")
                .location(new GeoJsonPoint(-21.9426, 64.1466))
                .latitude(64.1466)
                .longitude(-21.9426)
                .coverImageUrl("https://images.unsplash.com/photo-1504893524553-b855bce32c67?auto=format&fit=crop&w=1600&q=85")
                .heroVideoUrl("https://assets.mixkit.co/videos/preview/mixkit-green-northern-lights-over-a-starry-sky-42978-large.mp4")
                .bestSeason("Sept - March (Aurora) & June - August (Midnight Sun)")
                .currency("ISK (kr)")
                .language("Icelandic / English")
                .avgDailyBudgetUSD(210)
                .rating(4.9)
                .reviewCount(1850)
                .tags(List.of("Aurora", "Volcanoes", "Hot Springs", "Nature", "Adventure"))
                .places(List.of(
                    Place.builder()
                        .id("rey-1")
                        .name("The Blue Lagoon Geothermal Spa")
                        .category("Thermal Sanctuary")
                        .description("Mineral-rich geothermal waters heated by volcanic earth, surrounded by moss-covered lava fields.")
                        .imageUrl("https://images.unsplash.com/photo-1529963183134-61a90db47eaf?auto=format&fit=crop&w=800&q=80")
                        .entryFee("€65 - €90")
                        .openingHours("08:00 AM - 09:00 PM")
                        .rating(4.8)
                        .latitude(63.8804)
                        .longitude(-22.4495)
                        .bestTimeToVisit("Sunset into dark for stargazing")
                        .build()
                ))
                .build(),

            // 8. New York City, USA
            Destination.builder()
                .name("New York")
                .country("United States")
                .continent("Americas")
                .tagline("The relentless cultural and architectural capital of modern energy")
                .description("Iconic soaring art deco skyscrapers, world-leading performing arts on Broadway, sprawling Central Park, and the planet's most diverse global culinary neighborhoods.")
                .location(new GeoJsonPoint(-74.0060, 40.7128))
                .latitude(40.7128)
                .longitude(-74.0060)
                .coverImageUrl("https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?auto=format&fit=crop&w=1600&q=85")
                .heroVideoUrl("https://assets.mixkit.co/videos/preview/mixkit-aerial-view-of-central-park-in-new-york-42991-large.mp4")
                .bestSeason("April - June & September - November")
                .currency("USD ($)")
                .language("English")
                .avgDailyBudgetUSD(240)
                .rating(4.8)
                .reviewCount(6120)
                .tags(List.of("Skyscrapers", "Museums", "Broadway", "Gastronomy", "Nightlife"))
                .places(List.of(
                    Place.builder()
                        .id("nyc-1")
                        .name("Central Park & Bethesda Terrace")
                        .category("Urban Oasis")
                        .description("843 acres of scenic lakes, wooded paths, open meadows, and architectural terraces in the heart of Manhattan.")
                        .imageUrl("https://images.unsplash.com/photo-1518391846015-55a9cc003b25?auto=format&fit=crop&w=800&q=80")
                        .entryFee("Free")
                        .openingHours("06:00 AM - 01:00 AM")
                        .rating(4.9)
                        .latitude(40.7738)
                        .longitude(-73.9708)
                        .bestTimeToVisit("Morning stroll")
                        .build()
                ))
                .build(),

            // Munnar, Kerala, India
            Destination.builder()
                .name("Munnar")
                .country("India")
                .continent("Asia")
                .tagline("Rolling Emerald Tea Highlands & Shola Cloud Sanctuary")
                .description("Perched at 1,600m in Kerala's Western Ghats, Munnar is an internationally celebrated highland sanctuary renowned for sprawling emerald tea plantations, mist-covered mountain crags, endangered Nilgiri Tahr wildlife, and cascading waterfalls.")
                .location(new GeoJsonPoint(77.0595, 10.0889))
                .latitude(10.0889)
                .longitude(77.0595)
                .coverImageUrl("https://images.unsplash.com/photo-1596176530529-78163a4f7af2?auto=format&fit=crop&w=1600&q=85")
                .heroVideoUrl("/videos/aurora-loop.mp4")
                .bestSeason("September - March")
                .currency("INR (₹)")
                .language("Malayalam / English / Tamil")
                .avgDailyBudgetUSD(45)
                .rating(4.9)
                .reviewCount(3680)
                .tags(List.of("Highlands", "Tea Plantations", "Wildlife", "Mist Valleys", "Trekking"))
                .places(List.of(
                    Place.builder()
                        .id("mun-1")
                        .name("Eravikulam National Park (Rajamalai)")
                        .category("UNESCO Wildlife Sanctuary")
                        .description("High-altitude shola-grassland sanctuary harboring the endangered Nilgiri Tahr mountain goat, offering vistas of South India's highest peak Anamudi.")
                        .imageUrl("https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=800&q=80")
                        .entryFee("₹200 (~$2.50)")
                        .openingHours("07:30 AM - 04:00 PM")
                        .rating(4.9)
                        .latitude(10.1500)
                        .longitude(77.0600)
                        .bestTimeToVisit("Early morning safari")
                        .build(),
                    Place.builder()
                        .id("mun-2")
                        .name("Mattupetty Dam and Lake")
                        .category("Concrete Gravity Dam & Reservoir")
                        .description("A 160-foot tall concrete gravity dam built in 1953 surrounded by tea hills, where speedboating and peaceful lake vistas unfold.")
                        .imageUrl("https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80")
                        .entryFee("₹10 (Boating ₹300)")
                        .openingHours("09:30 AM - 05:00 PM")
                        .rating(4.8)
                        .latitude(10.1060)
                        .longitude(77.1245)
                        .bestTimeToVisit("Morning before winds ripple lake")
                        .build(),
                    Place.builder()
                        .id("mun-3")
                        .name("Top Station")
                        .category("High Altitude Cloud Belvedere")
                        .description("The highest point on the Munnar-Kodaikanal road at 1,880m offering 360-degree panoramic views over the Western Ghats and Theni valley.")
                        .imageUrl("https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=800&q=80")
                        .entryFee("₹25")
                        .openingHours("06:00 AM - 06:30 PM")
                        .rating(4.9)
                        .latitude(10.1250)
                        .longitude(77.2450)
                        .bestTimeToVisit("Sunrise or golden sunset")
                        .build(),
                    Place.builder()
                        .id("mun-4")
                        .name("Tata Tea Museum (KDHP)")
                        .category("Tea Heritage & Manufacturing")
                        .description("India's first tea museum at the Nallathanni Estate, showcasing century-old tea processing rollers, colonial archives, and live tea tastings.")
                        .imageUrl("https://images.unsplash.com/photo-1596176530529-78163a4f7af2?auto=format&fit=crop&w=800&q=80")
                        .entryFee("₹75 (~$1)")
                        .openingHours("09:00 AM - 05:00 PM")
                        .rating(4.8)
                        .latitude(10.0895)
                        .longitude(77.0545)
                        .bestTimeToVisit("Morning processing demonstration")
                        .build()
                ))
                .nearbyPlaces(List.of(
                    NearbyPlace.builder()
                        .id("nb-mun-1")
                        .name("Kolukkumalai Tea Estate & Ridge Peak")
                        .category("Highest Tea Mountain in the World")
                        .distance("35 km away")
                        .distanceKm(35)
                        .travelTime("1 hr 45 min via 4x4 Hill Jeep")
                        .description("World highest organic orthodox tea plantation standing at 7,900 feet, famed for legendary sunrises above an ocean of clouds.")
                        .imageUrl("https://images.unsplash.com/photo-1596176530529-78163a4f7af2?auto=format&fit=crop&w=800&q=80")
                        .entryFee("₹100 + Jeep Safari")
                        .rating(4.9)
                        .bestTimeToVisit("Early morning sunrise")
                        .build(),
                    NearbyPlace.builder()
                        .id("nb-mun-2")
                        .name("Marayoor Sandalwood Forest & Megalithic Dolmens")
                        .category("Ancient Sandalwood Reserve & Stone Age Relics")
                        .distance("40 km away")
                        .distanceKm(40)
                        .travelTime("1 hr 15 min via SH-17 Mountain Highway")
                        .description("Kerala only natural reserve of 65,000 fragrant sandalwood trees and prehistoric Neolithic burial chambers overlooking the Pambar River valley.")
                        .imageUrl("https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=800&q=80")
                        .entryFee("Free")
                        .rating(4.8)
                        .bestTimeToVisit("Morning forest walk")
                        .build(),
                    NearbyPlace.builder()
                        .id("nb-mun-3")
                        .name("Chinnar Wildlife Sanctuary")
                        .category("Deciduous Bio-Reserve & Tribal Trekking")
                        .distance("55 km away")
                        .distanceKm(55)
                        .travelTime("1 hr 40 min via scenic Ghat Road")
                        .description("Unique rain-shadow bio-reserve harboring the endangered grizzled giant squirrel, star tortoises, and tufted grey langurs.")
                        .imageUrl("https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=800&q=80")
                        .entryFee("₹100")
                        .rating(4.8)
                        .bestTimeToVisit("Morning wildlife trek")
                        .build(),
                    NearbyPlace.builder()
                        .id("nb-mun-4")
                        .name("Thekkady & Periyar Tiger Reserve")
                        .category("Tiger Reserve & Artificial Lake Safari")
                        .distance("90 km away")
                        .distanceKm(90)
                        .travelTime("2.5 hrs via Cardamom Hills Highway")
                        .description("Renowned wildlife sanctuary surrounding Lake Periyar where wild elephant herds, sambar deer, and tigers roam through evergreen forests.")
                        .imageUrl("https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80")
                        .entryFee("₹450 (with boat safari)")
                        .rating(4.9)
                        .bestTimeToVisit("Morning lake boat cruise")
                        .build()
                ))
                .build()
        );

        destinationRepository.saveAll(destinations);
    }
}
